apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  name: {{ include "karpenter.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
      protocol: TCP
  selector:
    {{- include "karpenter.labels" . | nindent 4 }}
