apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "karpenter.labels" . | nindent 4 }}
  name: {{ include "karpenter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
