# -- Overrides the chart's name
nameOverride: ""
# -- Overrides the chart's computed fullname
fullnameOverride: ""
# -- Number of replicas
replicaCount: 1

image:
  # -- Tag of the controller image
  tag: karpenter-clusterapi-controller
  # -- Image pull policy of the controller image
  pullPolicy: IfNotPresent

# -- Arguments for the controller
arguments: [ ]

securityContext:
  runAsNonRoot: true
  runAsUser: 65532

# -- Resources for the controller container
resources: { }

# -- Port for the health probe
healthProbePort:
  port: 8081
# -- Port for the metrics endpoint
metricsPort:
  port: 8080

# -- Environment variables for the controller container
env: { }

# -- Log level for the controller, default is "info"
logLevel: info
# -- Log output paths for the controller, default is "stdout"
logOutputPaths:
  - stdout
# -- Log error output paths for the controller, default is "stderr"
logErrorOutputPaths:
  - stderr

# -- Node selectors to schedule the pod to nodes with labels
nodeSelector: { }

# -- Affinity rules for scheduling the pod
affinity: { }

# -- Tolerations to allow the pod to be scheduled to nodes with taints
tolerations: [ ]

# -- Volumes for the pod
volumes: [ ]

# -- VolumeMounts for the controller container
volumeMounts: [ ]
